### ISSUE TITLE
Uprade Database version from    image: postgres:12.3-alpine to something higher.

### ISSUE THREAD

**Issue by makai77** [wagtail/docker-wagtail-develop#85] opened 2024-12-27 09:32 UTC
Am on Ubuntu 24.04LTS. The challenge is that the installation specicifes postgres 12, on the other hand Django only supports 13 or higher and that is a cause of pain. I resolved it but would appreciate if you update the compose.yaml file for a painless installation.

# What did i do?

#updated the postgres version from postgres:12.3-alpine
db:
    container_name: "db"
    image: postgres:13-alpine # or higher (also update to  psycopg3.1.8+ , if necessary  )

#Removed the existing PostgreSQL container:
docker rm -f db 

#Deleted the existing PostgreSQL data volume and let Docker reinitialize it with postgres:13-alpine
docker-compose down -v
docker-compose up

#run 
./setup-db.sh   # to initialize the database schema.

#Then i Continued following the documentation from : https://github.com/wagtail/docker-wagtail-develop

**Comment by zerolab** [comment] 2024-12-27 12:12
will be fixed by #82

**Comment by zerolab** [comment] 2024-12-27 12:12
also, closing as duplicate of #83.
Thank you for opening this

**Closed as duplicate by zerolab** 2024-12-27 12:12 UTC
